server:
  port: 8081
  error:
    include-message: always

logging:
  level:
    root: INFO
    com:
      jpworks:
        datajdbc: DEBUG

#By default the path for cxf is: /services
cxf:
  #Overriding the default path
  path: /soap

spring:
  profiles:
    active: local